"""Builds data/synthetic_claude.csv: training messages written by Claude (an AI), not real ones.

Written to cover scam schemes and look-alike normal messages that the hand-written seed data
does not have. It is marked as synthetic everywhere so nobody mistakes it for real data.
Never written by looking at data/eval/ test rows.
"""
import csv
from pathlib import Path

S, L = 1, 0
ROWS = [
# ---------------- SCAMS ----------------
# Telegram account takeover: "vote for my friend" and fake verification
("Assalomu alaykum! Jiyanim tanlovda qatnashyapti, iltimos ovoz bering, bir daqiqa vaqtingiz ketadi: konkurs-ovoz.top/vote", S, "uz", "account_takeover"),
("Salom, shu linkdan dugonamga ovoz berib yuborolmaysizmi? Telegram orqali kirish kerak ekan: t-golos.site", S, "uz", "account_takeover"),
("Привет! Проголосуй пожалуйста за мою племянницу в конкурсе, нужно войти через телеграм: golos-detki.online", S, "ru", "account_takeover"),
("Ассалому алайкум, синглим расм танловида қатнашяпти, илтимос овоз беринг: tanlov-ovoz.xyz", S, "uz", "account_takeover"),
("Telegram xavfsizlik xizmati: akkauntingiz 24 soat ichida o'chiriladi. Saqlab qolish uchun tasdiqlash kodini shu botga yuboring", S, "uz", "account_takeover"),
("Telegram Support: Your account has been reported for spam. Verify ownership within 12 hours or it will be deleted: telegram-verify.site", S, "en", "account_takeover"),
("Служба поддержки Telegram: на ваш аккаунт поступили жалобы. Подтвердите номер, отправив код из сообщения, иначе аккаунт будет удалён", S, "ru", "account_takeover"),
("Sizga Telegram Premium sovg'a qilindi! Faollashtirish uchun raqamingizni va kelgan kodni kiriting: tg-premium-gift.click", S, "uz", "account_takeover"),
("Вам подарили Telegram Premium на 1 год! Активируйте подарок по ссылке, войдя в аккаунт: premium-podarok.top", S, "ru", "account_takeover"),
("Do'stim, tasodifan senga kod yuborib qo'ydim, shu 5 xonali kodni menga tashlab yubora olasanmi? Shoshilinch", S, "uz", "account_takeover"),
("Ой, я случайно отправил тебе код на твой номер, перешли мне его пожалуйста, очень срочно", S, "ru", "account_takeover"),
("Hey, I accidentally sent my login code to your number, can you forward it to me? It's urgent", S, "en", "account_takeover"),
("Дўстим, сенга янглишиб код келди, шуни менга юбориб юбор илтимос", S, "uz", "account_takeover"),
("WhatsApp: hisobingizni boshqa qurilmaga ko'chirish so'raldi. Bekor qilish uchun SMS kodni javob qilib yuboring", S, "uz", "account_takeover"),
# Bank / payment app impersonation
("Payme xavfsizlik bo'limi: kartangizdan 2 400 000 so'm yechib olishga urinish bo'ldi. Bekor qilish uchun hozir kelgan kodni ayting", S, "uz", "bank_impersonation"),
("Hurmatli mijoz, Humo kartangiz muddati tugayapti. Yangilash uchun karta raqami, amal qilish muddati va SMS kodni yuboring", S, "uz", "bank_impersonation"),
("Ҳурматли мижоз, картангиз эскирган. Янгилаш учун карта рақами ва СМС кодни шу рақамга юборинг", S, "uz", "bank_impersonation"),
("Здравствуйте, вас беспокоит служба безопасности банка. По вашей карте зафиксирована подозрительная операция. Для отмены продиктуйте код из СМС", S, "ru", "bank_impersonation"),
("Ваша карта Uzcard будет заблокирована через 2 часа. Для сохранения доступа перейдите по ссылке и введите данные карты: uzcard-save.online", S, "ru", "bank_impersonation"),
("Kapitalbank: hisobingiz shubhali faoliyat sababli muzlatildi. Ochish uchun ilovani yangilang: kapital-update.apk", S, "uz", "bank_impersonation"),
("Click: Siz uchun 500 000 so'm keshbek hisoblandi. Olish uchun kartangizni tasdiqlang: click-cashback.xyz", S, "uz", "bank_impersonation"),
("Payme: на ваш счёт зачислен кэшбэк 350 000 сум. Чтобы получить, подтвердите карту по ссылке paymе-bonus.site", S, "ru", "bank_impersonation"),
("Your bank card has been temporarily suspended due to unusual activity. Confirm your card details here to restore access: secure-card-check.top", S, "en", "bank_impersonation"),
("Markaziy bank xodimiman. Sizning nomingizga firibgarlar kredit ochishga urinishyapti. Pulingizni saqlab qolish uchun xavfsiz hisobga o'tkazishimiz kerak", S, "uz", "bank_impersonation"),
("Я сотрудник Центрального банка. На ваше имя пытаются оформить кредит. Чтобы защитить деньги, переведите их на резервный счёт, который я продиктую", S, "ru", "bank_impersonation"),
("Bank xodimi: kartangizni himoyalash uchun ekranni namoyish qiling, men sizga qadam-baqadam ko'rsataman. Avval AnyDesk ilovasini o'rnating", S, "uz", "bank_impersonation"),
("Чтобы мы могли отменить списание, установите приложение для удалённой поддержки и сообщите мне код доступа", S, "ru", "bank_impersonation"),
("Hurmatli mijoz! Uzum Bank kartangizga 3 000 000 so'mlik kredit limiti ochildi. Faollashtirish uchun kartangiz ma'lumotlarini kiriting: uzum-limit.top", S, "uz", "bank_impersonation"),
("Ucell: SIM-kartangiz eskirgan va 24 soatda o'chiriladi. Yangilash uchun kelgan kodni operatorga ayting", S, "uz", "telecom"),
("Beeline: ваш номер будет отключён из-за окончания договора. Для продления назовите код, который придёт в СМС", S, "ru", "telecom"),
("Mobil operator: raqamingizni qayta ro'yxatdan o'tkazish kerak. Pasport seriyasi va SMS kodni yuboring, aks holda raqam bloklanadi", S, "uz", "telecom"),
# Prizes, giveaways, lottery
("Tabriklaymiz! Siz Humo lotereyasida 10 000 000 so'm yutdingiz. Pulni olish uchun 150 000 so'm xizmat haqi to'lang", S, "uz", "prize"),
("Поздравляем! Ваш номер выиграл автомобиль Chevrolet Tracker в розыгрыше. Для оформления оплатите пошлину 300 000 сум", S, "ru", "prize"),
("Uzum Market 3 yilligi! Har 100 nafar ishtirokchidan biri iPhone yutadi. Ishtirok etish: uzum-yubiley.fun", S, "uz", "prize"),
("Табриклаймиз! Сиз телефон ютиб олдингиз. Совғани олиш учун етказиб бериш ҳақи 99 000 сўм тўланг", S, "uz", "prize"),
("Congratulations! You were selected for a $500 Amazon gift card. Claim it within 30 minutes: gift-claim-now.xyz", S, "en", "prize"),
("Instagram giveaway g'olibisiz! Sovg'ani olish uchun profilga yozing va yetkazib berish uchun 50 000 so'm oldindan tashlang", S, "uz", "prize"),
("Вы стали победителем розыгрыша от блогера! Чтобы забрать приз, переведите 70 000 сум за доставку на карту <CARD>", S, "ru", "prize"),
("Navro'z aksiyasi: Artel har bir xaridorga konditsioner sovg'a qilmoqda! Anketani to'ldiring: artel-sovga.online", S, "uz", "prize"),
# Fake grants, scholarships, admission
("El-yurt umidi jamg'armasi nomidan: siz grantga tavsiya etildingiz. Hujjatlarni rasmiylashtirish uchun 350 000 so'm to'lov qiling", S, "uz", "fake_grant"),
("Xorijda bepul o'qish! 100% grant kafolati bilan. Faqat ro'yxatdan o'tish badali 1 000 000 so'm. Joylar soni cheklangan", S, "uz", "fake_grant"),
("Гарантируем поступление в Корею на грант. Оплата консультации 800$ заранее, остальное после визы", S, "ru", "fake_grant"),
("DTM test javoblari sotiladi! 100% to'g'ri javoblar, imtihondan bir kun oldin. Narxi 500 000 so'm, oldindan to'lov", S, "uz", "exam_fraud"),
("Ответы на вступительные тесты DTM! Гарантия 100%, предоплата 50%. Пишите в личку", S, "ru", "exam_fraud"),
("Universitetga kontraktsiz o'qishga kiritib qo'yaman, rektoratda tanishlarim bor. 2000$ oldindan beriladi", S, "uz", "exam_fraud"),
("Hurmatli abituriyent, siz talabalikka qabul qilindingiz! Shartnomani rasmiylashtirish uchun 300 000 so'mni shu kartaga o'tkazing", S, "uz", "fake_grant"),
# Advance fee, loans
("Kredit tarixingiz muhim emas! 50 000 000 so'mgacha kredit 1 kunda. Faqat sug'urta to'lovi 500 000 so'm oldindan", S, "uz", "loan_scam"),
("Одобрен кредит на 30 000 000 сум без справок! Для получения оплатите страховку 400 000 сум на карту менеджера", S, "ru", "loan_scam"),
("Кредитингиз тасдиқланди! Пулни олиш учун аввал 200 000 сўм суғурта тўловини амалга оширинг", S, "uz", "loan_scam"),
("Your loan of $5,000 is approved! To release the funds, pay a one-time processing fee of $150 via gift card", S, "en", "loan_scam"),
("Mikroqarz 5 daqiqada, pasportsiz! Faqat kartangiz raqami va SMS kodni yuboring, pul darhol tushadi", S, "uz", "loan_scam"),
("Мерос пулингиз бор: чет элда қариндошингиз сизга 50 000$ қолдирган. Ҳужжатлар учун 300$ тўланг", S, "uz", "advance_fee"),
("Siz nomingizga xorijdan 2000$ pul o'tkazmasi keldi. Uni qabul qilish uchun komissiya 100 000 so'm to'lashingiz kerak", S, "uz", "advance_fee"),
("На ваше имя поступил международный перевод 1500$. Для зачисления оплатите комиссию 120 000 сум", S, "ru", "advance_fee"),
# Jobs, easy money, investment
("Koreyaga ishga yuboramiz! Oyiga 2500$ maosh, viza kafolatlangan. Hujjatlar uchun 1500$ oldindan to'lanadi", S, "uz", "job_scam"),
("Работа в Польше на заводе, зарплата 1800€. Виза и билет за наш счёт, только оплатите оформление 600$", S, "ru", "job_scam"),
("Uyda o'tirib kuniga 500 000 so'm ishlang! Faqat telefon kerak. Boshlash uchun 99 000 so'm to'lab kursga yoziling", S, "uz", "easy_money"),
("Подработка: ставь лайки на товары и получай до 300 000 сум в день. Для старта внеси депозит 200 000 сум", S, "ru", "easy_money"),
("Vazifa: mahsulotlarga baho qo'ying va har biri uchun pul oling. Keyingi bosqichga o'tish uchun hisobingizni 300 000 so'mga to'ldiring", S, "uz", "easy_money"),
("Remote job: earn $200 per day liking videos. Pay a $30 registration fee to start today", S, "en", "easy_money"),
("Kartangizni ijaraga bering, har oy 1 000 000 so'm olasiz. Faqat karta va SIM kartani bizga berasiz", S, "uz", "money_mule"),
("Нужны карты для приёма платежей, платим 500 000 сум за каждую карту в неделю. Ничего делать не нужно", S, "ru", "money_mule"),
("Uzum aksiyalariga sarmoya kiriting! Har hafta 25% foyda kafolatlanadi. Minimal sarmoya 1 000 000 so'm", S, "uz", "investment"),
("Крипто-бот приносит 40% в месяц без риска! Вложите от 100$ и получайте прибыль каждый день", S, "ru", "investment"),
("Инвестиция қилинг ва 1 ойда пулингизни икки баробар қилинг! Кафолат 100%. Жойлар чекланган", S, "uz", "investment"),
("Double your USDT in 24 hours! Send any amount to our wallet and get 2x back. Limited offer", S, "en", "investment"),
("P2P orqali tez pul: siz pul qabul qilasiz va boshqa kartaga o'tkazasiz, har bir o'tkazmadan 5% sizniki", S, "uz", "money_mule"),
# Marketplace, rentals, tickets
("Assalomu alaykum, OLX'dagi mahsulotingizni sotib olaman. Pulni OLX Delivery orqali tashladim, olish uchun bu havolaga kirib karta ma'lumotlarini kiriting: olx-dostavka.site", S, "uz", "marketplace"),
("Здравствуйте, я оплатил ваш товар через безопасную сделку OLX. Чтобы получить деньги, введите данные карты по ссылке olx-pay-uz.top", S, "ru", "marketplace"),
("Mahsulotingiz uchun to'lov qildim, lekin bank tasdiqlash kodi sizning raqamingizga keldi, shuni menga yuborib bering", S, "uz", "marketplace"),
("Telefonni 30% chegirma bilan sotaman, faqat bugun. To'liq oldindan to'lov, keyin pochta orqali jo'nataman", S, "uz", "marketplace"),
("Продаю iPhone 16 Pro за полцены, срочно. Только полная предоплата на карту, доставка из другого города", S, "ru", "marketplace"),
("Kvartira ijaraga, Chilonzorda, juda arzon. Ko'rishdan oldin 1 oylik to'lovni oldindan tashlang, aks holda boshqaga beraman", S, "uz", "rental"),
("Сдаю квартиру посуточно в центре Ташкента. Для брони переведите 100% предоплату, ключи передам курьером", S, "ru", "rental"),
("Umra ziyoratiga yo'llanma 50% chegirma bilan! Joy band qilish uchun bugun 5 000 000 so'm oldindan to'lang", S, "uz", "travel_scam"),
("Авиабилеты в Стамбул в 3 раза дешевле! Оплата только переводом на карту, билет пришлём после оплаты", S, "ru", "travel_scam"),
("Green Card lotereyasida g'olib bo'ldingiz! Vizani rasmiylashtirish uchun 500$ to'lov qiling", S, "uz", "travel_scam"),
("Konsertga chiptalar tugadi, lekin menda bor. Narxi ikki baravar, oldindan kartaga tashlaysiz", S, "uz", "marketplace"),
# Parcels, customs, couriers
("Pochta: posilkangiz bojxonada ushlab qolindi. Bojxona to'lovi 87 000 so'm, to'lash uchun: uzpost-tolov.xyz", S, "uz", "parcel"),
("Ваша посылка задержана на таможне. Оплатите пошлину 65 000 сум в течение 24 часов, иначе она будет возвращена: pochta-uz.online", S, "ru", "parcel"),
("Kuryer: buyurtmangizni yetkazib bera olmadim, manzilni tasdiqlash uchun ilovani yuklab oling: delivery-track.apk", S, "uz", "parcel"),
("Your package could not be delivered. Update your address and pay a $1.99 redelivery fee: parcel-redeliver.top", S, "en", "parcel"),
# Relatives, friends in trouble
("Ona, bu men, telefonim buzildi, bu yangi raqamim. Juda shoshilinch 2 000 000 so'm kerak, shu kartaga tashlab yuboring, keyin tushuntiraman", S, "uz", "relative"),
("Мам, это я, пишу с чужого номера. Попал в неприятность, срочно нужно 3 млн, переведи на эту карту, только папе не говори", S, "ru", "relative"),
("Дада, бу менман, телефоним ўғирланди. Тезда пул керак, шу картага ташлаб юборинг, ҳеч кимга айтманг", S, "uz", "relative"),
("Akang avariyaga tushdi, militsiya xonasida o'tiribmiz. Ishni yopish uchun hozir 5 000 000 so'm kerak, hech kimga aytmang", S, "uz", "relative"),
("Ваш сын попал в ДТП, нужна срочно сумма для решения вопроса. Передайте деньги нашему курьеру", S, "ru", "relative"),
("Do'stim, akkauntim buzildi, bu yangi profilim. Qarzga 800 000 so'm berib tur, ertaga qaytaraman. Kartaga tashla", S, "uz", "relative"),
# Government, fines, utilities, summons
("YHXBB: avtomobilingizga 1 250 000 so'm jarima yozildi. 50% chegirma bilan to'lash uchun: yhxbb-jarima.online", S, "uz", "gov"),
("ГАИ: на ваш автомобиль выписан штраф. Оплатите в течение 24 часов со скидкой 50% по ссылке gai-shtraf.site", S, "ru", "gov"),
("Hududgazta'minot: gaz uchun 540 000 so'm qarzingiz bor. Bugun to'lamasangiz gaz o'chiriladi. To'lov: gaz-qarz.top", S, "uz", "gov"),
("Elektr energiyasi uchun qarzdorlik: ertaga soat 9 da tok uziladi. Darhol ushbu kartaga 320 000 so'm o'tkazing", S, "uz", "gov"),
("Soliq qo'mitasi: sizga 1 800 000 so'm soliq qaytarilishi kerak. Olish uchun karta raqami va SMS kodni yuboring", S, "uz", "gov"),
("Налоговая: вам положен возврат налога 1 200 000 сум. Для получения заполните анкету и укажите данные карты: soliq-vozvrat.xyz", S, "ru", "gov"),
("Ijtimoiy yordam: siz bir martalik 2 000 000 so'm nafaqa olish huquqiga egasiz. Ariza berish uchun: yordam-uz.site", S, "uz", "gov"),
("Ҳарбий комиссариат: сизга чақирув қоғози берилган. Келмаслик учун жаримани шу ерда тўланг: harbiy-jarima.click", S, "uz", "gov"),
("Prokuratura xodimi: sizning kartangiz orqali noqonuniy o'tkazma bo'lgan. Jinoiy ishni yopish uchun xavfsiz hisobga pul o'tkazing", S, "uz", "threat"),
("Следственный комитет: вы проходите свидетелем по делу о мошенничестве. Для защиты средств переведите их на безопасный счёт", S, "ru", "threat"),
("Sizning intim suratlaringiz bizda. 24 soat ichida 500$ tashlamasangiz, barcha do'stlaringizga yuboramiz", S, "uz", "threat"),
("We hacked your camera and recorded you. Pay $300 in Bitcoin within 48 hours or the video goes to all your contacts", S, "en", "threat"),
# Malicious apps and files
("Bu sening rasmingmi? Juda kulgili chiqibdi 😂 rasm.jpg.apk", S, "uz", "apk"),
("Смотри, тебя сфоткали на свадьбе: foto_svadba.apk", S, "ru", "apk"),
("To'y taklifnomasi: ochish uchun yuklab oling — taklifnoma.apk", S, "uz", "apk"),
("Тўйга таклифнома: юклаб олинг ва очинг — taklif.apk", S, "uz", "apk"),
("Davlat xizmatlari yangi ilovasi: barcha jarimalar va qarzlarni tekshiring. Yuklab oling: mygov-new.apk", S, "uz", "apk"),
("Ваша накладная во вложении, установите приложение для просмотра: nakladnaya_2026.apk", S, "ru", "apk"),
("Siz uchun hujjat yuborildi, ko'rish uchun dastur o'rnating: hujjat_korish.apk", S, "uz", "apk"),
("Check this invoice and install the viewer app: invoice_viewer.apk", S, "en", "apk"),
# Charity, romance, misc
("Kasal bolaga yordam bering! Operatsiyaga 30 000$ yetmayapti, har qanday summa muhim. Karta: <CARD>", S, "uz", "charity"),
("Срочно! Девочке нужна операция, сбор на карту матери. Любая сумма поможет, перешлите всем", S, "ru", "charity"),
("I'm a US army doctor in Syria. I want to send you a box with my savings, just pay the shipping company fee", S, "en", "romance"),
("Salom, men chet eldagi shifokorman, sizga yoqib qoldim. Sovg'a jo'natdim, bojxona to'lovini qilib qo'ysangiz yetib keladi", S, "uz", "romance"),
("Telegram kanalimizga qo'shiling va har kuni bepul signallar bilan 100$ ishlang! Faqat VIP guruhga kirish 50$", S, "uz", "investment"),
("Квартира по наследству оформлена на вас. Для вступления в права оплатите услуги нотариуса 2 000 000 сум", S, "ru", "advance_fee"),
("Siz tanlovda g'olib bo'ldingiz, sovg'ani olish uchun shaxsingizni tasdiqlang: pasport rasmi va karta raqamini yuboring", S, "uz", "prize"),
("Assalomu alaykum, men Click xodimiman. Sizning profilingizda xatolik bor, to'g'rilashim uchun parolingizni ayting", S, "uz", "bank_impersonation"),
("Hurmatli foydalanuvchi, Payme akkauntingizdan noma'lum qurilmaga kirildi. Bu siz bo'lmasangiz, kodni javob tariqasida yuboring", S, "uz", "bank_impersonation"),
("Uzum Nasiya: muddati o'tgan qarzingiz bor! Bugun to'lamasangiz ish sudga beriladi. To'lov havolasi: nasiya-tolov.top", S, "uz", "threat"),
("Коллекторы: у вас просрочка по займу. Если не оплатите сегодня до 18:00 на карту <CARD>, приедем домой и на работу", S, "ru", "threat"),
("Вы выиграли путёвку на двоих в Дубай! Оплатите только налог 10% от стоимости путёвки", S, "ru", "prize"),
("Pensiya jamg'armasi: pensiyangiz qayta hisoblandi, 4 000 000 so'm qo'shimcha to'lov bor. Olish uchun karta ma'lumotlarini kiriting: pensiya-plus.site", S, "uz", "gov"),
("Ҳурматли фуқаро, сизнинг номингизга 3 та жарима бор. Тўламасангиз чегарадан чиқа олмайсиз. Тўлов: jarima-uz.top", S, "uz", "gov"),
("Your Apple ID has been locked. Verify your identity now to avoid permanent deletion: appleid-verify-secure.xyz", S, "en", "account_takeover"),
("Google: someone has your password. Reset it immediately here: google-security-reset.top", S, "en", "account_takeover"),
("Instagram: profilingiz mualliflik huquqi buzilgani uchun o'chiriladi. E'tiroz bildirish: insta-copyright.help", S, "uz", "account_takeover"),
("Ваш аккаунт Instagram будет удалён за нарушение авторских прав. Подайте апелляцию по ссылке: ig-appeal.site", S, "ru", "account_takeover"),
("Assalomu alaykum, men sizning sinfdoshingizman, raqamim o'zgardi. Kichik iltimosim bor: kartangizga pul tashlayman, naqd qilib bera olasizmi?", S, "uz", "money_mule"),
("Привет, это твой одноклассник, сменил номер. Можно я скину деньги тебе на карту, а ты переведёшь их другу? Свою карту заблокировали", S, "ru", "money_mule"),
("Ish taklifi: kuryer, kunlik to'lov 400 000 so'm. Ishga olish uchun forma va sug'urta uchun 150 000 so'm to'laysiz", S, "uz", "job_scam"),
("Онлайн-курс трейдинга с гарантией заработка 1000$ в месяц. Стоимость 3 000 000 сум, возврата нет", S, "ru", "investment"),
("Hajga navbatsiz yuboramiz! Hujjatlarni tez rasmiylashtiramiz, oldindan 3000$ to'lov", S, "uz", "travel_scam"),
("Bepul internet paketi! Ucell 50 GB sovg'a qilyapti, olish uchun havolaga kiring va raqamingizni tasdiqlang: ucell-gift.click", S, "uz", "telecom"),
("Сизнинг Telegram аккаунтингизга бошқа қурилмадан кирилди. Агар бу сиз бўлмасангиз, кодни ушбу ботга юборинг", S, "uz", "account_takeover"),
("Aka, kechirasiz, xato raqamga 500 000 so'm tashlab yubordim. Iltimos qaytarib yuboring, shu kartaga", S, "uz", "fake_transfer"),
("Извините, я по ошибке перевёл вам 400 000 сум. Верните, пожалуйста, на эту карту, очень нужно", S, "ru", "fake_transfer"),
("Kartangizga 1 200 000 so'm tushdi (Click). Iltimos, xato tushgan pulni ushbu raqamga qaytaring", S, "uz", "fake_transfer"),

# ---------------- NORMAL MESSAGES (look-alikes and everyday) ----------------
# Real bank and payment notifications
("Click: Kartangizdan 45 000 so'm yechildi. Mahsulot: Korzinka. Balans: 1 230 000 so'm", L, "uz", "bank_notification"),
("Payme: Uzmobile uchun 30 000 so'm to'lov muvaffaqiyatli amalga oshirildi", L, "uz", "bank_notification"),
("HUMO: kartaga 2 500 000 so'm kelib tushdi. Jo'natuvchi: INHA University. Balans: 2 740 000", L, "uz", "bank_notification"),
("Uzcard: Списание 120 000 сум, Makro. Баланс: 860 000 сум", L, "ru", "bank_notification"),
("Kod: 482913. Uni hech kimga, hatto bank xodimiga ham aytmang. Click", L, "uz", "otp_sms"),
("Код подтверждения: 551029. Никому не сообщайте этот код. Payme", L, "ru", "otp_sms"),
("Your verification code is 330187. Do not share this code with anyone.", L, "en", "otp_sms"),
("Uzum Bank: kredit bo'yicha navbatdagi to'lov 15-oktabr. Summa: 610 000 so'm. Ilovada to'lashingiz mumkin", L, "uz", "bank_notification"),
("Kapitalbank: kartangiz muddati noyabrda tugaydi. Yangi kartani istalgan filialda bepul olishingiz mumkin", L, "uz", "bank_notification"),
("Ваша карта будет перевыпущена автоматически. Новую карту можно получить в отделении банка с паспортом", L, "ru", "bank_notification"),
("Hurmatli mijoz! Ilovamizning yangi versiyasi chiqdi. App Store yoki Google Play orqali yangilang", L, "uz", "bank_notification"),
("Uzum Market: buyurtmangiz #48213 topshirish punktiga yetkazildi. 5 kun ichida olib keting", L, "uz", "service"),
("Ваш заказ передан в службу доставки. Отслеживание: uzum.uz/orders", L, "ru", "service"),
("Your order has shipped and will arrive on Thursday. Track it in the app.", L, "en", "service"),
("Hududgazta'minot: oktyabr oyi uchun hisob 64 000 so'm. To'lovni Click yoki Payme orqali amalga oshirishingiz mumkin", L, "uz", "service"),
("Uzmobile: balansingizda 2 000 so'm qoldi. Hisobni to'ldirishni unutmang", L, "uz", "service"),
("Beeline: вам начислено 5 ГБ бонусного интернета по тарифу. Проверить остаток: *102#", L, "ru", "service"),
("Shifoxonaga yozuvingiz tasdiqlandi: 12-oktabr, soat 10:30, 214-xona", L, "uz", "service"),
("my.gov.uz: arizangiz ko'rib chiqildi. Natijani shaxsiy kabinetingizda ko'rishingiz mumkin", L, "uz", "official_post"),
("Davlat xizmatlari markazi: pasportingiz tayyor. Uni hujjat bilan kelib olib ketishingiz mumkin", L, "uz", "official_post"),
("El-yurt umidi jamg'armasi: suhbat jadvali rasmiy saytda e'lon qilindi. Batafsil: el-yurt.uz", L, "uz", "official_post"),
("Ташкент шаҳар ҳокимлиги: 15 октябрь куни шаҳар марказида субботник ўтказилади", L, "uz", "official_post"),
("Министерство цифровых технологий объявило конкурс стартапов. Заявки принимаются на официальном сайте до 1 декабря", L, "ru", "official_post"),
("INHA University: kuzgi semestr imtihonlari jadvali e-classda joylandi", L, "uz", "official_post"),
# News and warnings (they mention scam words, but nobody is tricked)
("Markaziy bank ogohlantiradi: bank xodimlari hech qachon SMS kod yoki karta ma'lumotlarini so'ramaydi", L, "uz", "warning"),
("Ichki ishlar vazirligi: \"ovoz bering\" degan havolalarga kirmang, ular Telegram akkauntingizni o'g'irlaydi", L, "uz", "warning"),
("Внимание: мошенники рассылают ссылки «проголосуй за племянницу». Не вводите номер и код из СМС", L, "ru", "warning"),
("Eslatma: OLX hech qachon to'lovni qabul qilish uchun karta ma'lumotlarini kiritishni so'ramaydi", L, "uz", "warning"),
("Don't install .apk files sent in chats, even from friends. Real banks never send apps this way.", L, "en", "warning"),
("Kun.uz: Toshkentda firibgarlar guruhi ushlandi, ular o'zini bank xodimi deb tanishtirgan", L, "uz", "news"),
("Газета.uz: число кибермошенничеств с банковскими картами выросло, эксперты советуют подключить двухфакторную защиту", L, "ru", "news"),
("Kecha menga ham \"kartangiz bloklandi\" deb qo'ng'iroq qilishdi, kodni aytmadim, darhol trubkani qo'ydim", L, "uz", "report"),
("Onamga bugun \"o'g'lingiz avariyaga tushdi\" deb yozishgan ekan, xayriyat menga qo'ng'iroq qilib so'radi", L, "uz", "report"),
("Мне сегодня звонили якобы из банка, просили код. Я не сказал, будьте внимательны", L, "ru", "report"),
# Everyday personal messages, including real money talk
("Ona, darsdan keyin kutubxonaga boraman, kechroq qaytaman", L, "uz", "personal"),
("Aka, ertaga to'yga soat nechada boramiz?", L, "uz", "personal"),
("Do'stim, kecha qarzga olgan 100 000 so'mni hozir kartangga tashladim, tekshirib ko'r", L, "uz", "personal"),
("Мама, я перевёл тебе деньги за коммуналку, посмотри пришли ли", L, "ru", "personal"),
("Dadajon, kontrakt to'lovini qildim, chekni yuboraman", L, "uz", "personal"),
("Brat, futbolga kim boradi? 20:00 da maydonda", L, "uz", "personal"),
("Салом, эртага дарсга келасанми? Ўқитувчи тест олармиш", L, "uz", "personal"),
("Нон олиб кел, уйда тугабди", L, "uz", "personal"),
("Can you send me the lecture slides from today?", L, "en", "personal"),
("Привет! Как дела? Давно не виделись, давай встретимся в выходные", L, "ru", "personal"),
("Tabriklayman, imtihondan yaxshi o'tibsan! Kechqurun choyxonaga boramizmi?", L, "uz", "personal"),
("Ustoz, uy vazifasini qachongacha topshirishimiz kerak?", L, "uz", "personal"),
("Guruhdoshlar, ertaga INHA kutubxonasida soat 3 da loyiha bo'yicha yig'ilamiz", L, "uz", "personal"),
("Opa, bozordan kelayotganda pomidor va kartoshka olib keling", L, "uz", "personal"),
("Happy birthday! Wishing you a great year ahead 🎉", L, "en", "personal"),
("Поздравляю с днём рождения! Здоровья и счастья!", L, "ru", "personal"),
("Тўйимизга таклиф қиламиз! 20 октябрь, соат 18:00, \"Navro'z\" тўйхонаси", L, "uz", "personal"),
("To'yimizga taklif qilamiz! 25-oktabr, soat 17:00, Chilonzor tumani, \"Oqsaroy\" to'yxonasi", L, "uz", "personal"),
("Akajon, telefoningizni zaryad qiling, qo'ng'iroq qilsam o'chiq", L, "uz", "personal"),
("Я опоздаю минут на 15, пробка на Амира Темура", L, "ru", "personal"),
# Work, business, legitimate sales
("Hamkasblar, ertangi yig'ilish soat 10:00 ga ko'chirildi", L, "uz", "work"),
("Коллеги, отчёт за сентябрь нужно сдать до пятницы", L, "ru", "work"),
("Please review the attached presentation before Monday's meeting.", L, "en", "work"),
("Do'konimizda kuzgi chegirmalar: barcha kurtkalar 20% arzon. Manzil: Chorsu bozori, 3-qator", L, "uz", "business_ad"),
("Новое меню в нашей кофейне! Приходите на дегустацию в субботу, вход свободный", L, "ru", "business_ad"),
("Ingliz tili kurslariga qabul davom etmoqda. Birinchi dars bepul. Manzil: Yunusobod, 4-kvartal", L, "uz", "business_ad"),
("Assalomu alaykum, OLX'dagi velosipedingiz hali sotuvdami? Kechqurun ko'rgani kelsam bo'ladimi?", L, "uz", "marketplace_legit"),
("Здравствуйте, диван ещё актуален? Могу приехать посмотреть завтра, оплачу наличными при встрече", L, "ru", "marketplace_legit"),
("Telefonni ko'rib chiqdim, menga yoqdi. Uchrashganda naqd pul beraman, qayerda ko'rishamiz?", L, "uz", "marketplace_legit"),
("Kvartira ijaraga beriladi, Yunusobod. Avval ko'rib chiqing, keyin shartnoma tuzamiz. Rieltorsiz", L, "uz", "marketplace_legit"),
("Hi, is the laptop still available? I can meet tomorrow and pay in cash", L, "en", "marketplace_legit"),
("Avtomobil sotiladi, Cobalt 2022. Ko'rish va texnik ko'rikdan o'tkazish mumkin. Faqat shaxsan uchrashuvda", L, "uz", "marketplace_legit"),
("Kurs to'lovini Click orqali ilovada qilsangiz bo'ladi, chekni administratorga ko'rsatasiz", L, "uz", "service"),
("Hurmatli talabalar! Stipendiya kartalarga 5-oktabr kuni o'tkaziladi", L, "uz", "official_post"),
("Zakaz qilgan kitobingiz keldi, ertaga do'konga kelib olib keting", L, "uz", "service"),
("Ваш врач записал вас на анализы на 9:00 завтра. Не ешьте за 8 часов до сдачи", L, "ru", "service"),
("Bugun soat 19:00 da mahallamizda yig'ilish bo'ladi, hamma kelsin", L, "uz", "personal"),
("Сегодня в 18:00 родительское собрание в 5 «Б» классе", L, "ru", "personal"),
("Toshkent metrosi: 12-oktabr kuni Chilonzor yo'nalishida ta'mirlash ishlari olib boriladi", L, "uz", "news"),
("Yangi iPhone Uzbekistonda sotuvga chiqdi, narxi rasmiy dilerlarda 18 million so'mdan", L, "uz", "news"),
("Курс доллара на сегодня: 12 650 сум. ЦБ Узбекистана", L, "ru", "news"),
("O'zbekiston terma jamoasi bugun soat 20:00 da o'yin o'tkazadi", L, "uz", "news"),
("Uzum Market'da bugun 11.11 aksiyasi: chegirmalarni ilovada ko'ring", L, "uz", "business_ad"),
("Click ilovasida yangi funksiya: endi kommunal to'lovlarni avtomatik to'lash mumkin", L, "uz", "bank_notification"),
("Payme: oylik obuna to'lovi 25 000 so'm muvaffaqiyatli yechildi (Netflix)", L, "uz", "bank_notification"),
("Ваш платёж на сумму 75 000 сум за интернет успешно проведён. Спасибо!", L, "ru", "bank_notification"),
("Do'stim, kecha restoranda men to'lagandim, ulushing 85 000 so'm, qachon qulay bo'lsa tashlab qo'y", L, "uz", "personal"),
("Сколько я тебе должен за билеты? Скинь номер карты, переведу", L, "ru", "personal"),
("Ona, dorixonadan dori oldim, pulini o'zim to'ladim, xavotir olmang", L, "uz", "personal"),
("Talabalar uchun hackathon! Ro'yxatdan o'tish bepul, g'oliblarga sovrinlar. Batafsil: it-park.uz", L, "uz", "official_post"),
("Grant natijalari 20-noyabrda rasmiy saytda e'lon qilinadi. Hech qanday to'lov talab qilinmaydi", L, "uz", "official_post"),
("Vaqtincha ishga odam kerak: kafe, ofitsiant, kunlik ish haqi. Murojaat shaxsan, Mirzo Ulug'bek tumani", L, "uz", "work"),
("Вакансия: бухгалтер в торговую компанию. Отправьте резюме на hh.uz, собеседование в офисе", L, "ru", "work"),
("Yangi ish joyimda birinchi oylik keldi, bugun men mehmon qilaman!", L, "uz", "personal"),
("Bayramingiz bilan! Sog'lik va baxt tilayman", L, "uz", "personal"),
("Uyga kelayotganda dorixonadan paratsetamol olib keling", L, "uz", "personal"),
("Telegram: Kod 74521. Uni hech kimga bermang, hatto Telegram xodimlariga ham", L, "uz", "otp_sms"),
("Login code: 61842. Do not give this code to anyone, even if they say they are from Telegram!", L, "en", "otp_sms"),
]


def main() -> None:
    out = Path(__file__).resolve().parent.parent / "data" / "synthetic_claude.csv"
    with open(out, "w", encoding="utf-8", newline="") as f:
        w = csv.writer(f, lineterminator="\n")
        w.writerow(["text", "label", "lang", "category", "source"])
        for text, label, lang, cat in ROWS:
            w.writerow([text, label, lang, cat, "synthetic_claude"])
    print(f"{len(ROWS)} rows -> {out}")


if __name__ == "__main__":
    main()
